import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rhu Match Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      

      <main className={styles.main}>

      </main>


      {/* //contains the images for to swipe through */}
      <div className={styles.card}>



        <div className={styles.cardImage}>
          {/* <Image src="/images/1.jpg" alt="1" width={300} height={300} /> */}
        </div>


        
        <div className='btcContainer'>
          <button className={styles.buttonNope}>
          <h2 className='styels.textin'>{'<'}NoPe</h2>
          </button>
          <button className={styles.button}>
          <h2 className='styels.textin'>LiKe{'>'}</h2>
          </button>
        </div>
      </div>

    </div>
  );
}
