import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rhu Match Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      

      <main className={styles.main}>

      </main>


      {/* //contains the images for to swipe through */}
      <div className={styles.card}>






        {/* //like and cancel buttons will be in the div below  */}
        <div>

        </div>



      </div>

    </div>
  );
}
